version: '3'

services:
  api:
    image: exchange-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-api
    command: bash -c "yarn && yarn start"
    restart: always
    volumes:
      - .:/app
    working_dir: '/app'
    ports:
      - '80:3000'
    networks:
      exchange-network:
        ipv4_address: 1.0.0.2

  mongo:
    image: mongo:3.4
    container_name: mongodb
    restart: always
    volumes:
      - ./volumes/mongo:/data/db
    networks:
      exchange-network:
        ipv4_address: 1.0.0.3

networks:
  exchange-network:
    driver: bridge
    ipam:
      config:
        - subnet: 1.0.0.0/24
